### ISSUE TITLE
Requests list

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/paymaster#36]
This ticket comprises meeting summaries, highlighting emerging requests that have arisen as a consequence: 

- [x] add function `skipTime` (for QA)
- [x] change parameter name (`id` :arrow_right:  `validator_id`) in `setNodesAmount` and `setActiveNodes` functions
- [x] make separate call for `paidUntil`
- [x] handle "pay for 7 months + pay for 7 months" case
- [x] fix skipTime 
- [x] Limit validators withdrawal to a 1 day of current month
- [x] ["RemoveValidator"](https://skale-innocent-nasty.legacy-explorer.skalenodes.com/tx/0x6af157260b265613f6946602b0b4cd7082c2a87b25e809add8dbd517ae5ed42a) transaction fails (["AddValidator"](https://skale-innocent-nasty.legacy-explorer.skalenodes.com/tx/0x6af157260b265613f6946602b0b4cd7082c2a87b25e809add8dbd517ae5ed42a))
- [x] Reject payments if SKL price is outdated
- [x] Add version
- [x] Add call `getRewardAmount`
- [x] Add call `getNodesNumber`
- [x] Add call `getValidatorsNumber`
- [x] Provide getter for available rewards amount
- [x] Deal with unclaimed rewards of removing validator
- [x] Add events
- [x] #64
- [x] #61
- [ ] Add inline documentation
- [ ] Allow Admin to call `setSklPrice`
- [ ] add automatic contract verify
- [ ] Add paymaster to `skale-contracts`
- [ ] Reduce contract size of `FastForwardPaymaster`

Required scripts:

- [x] initialization based on mainnet smart contracts
- [ ] initialization verification
- [ ] upgrade

**Comment by payvint** [comment]
Can I add one more?:)

- [ ] Unit tests

**Comment by yatsunastya** [comment]
- [ ] add automatic contract verify

**Comment by PolinaKiporenko** [comment]
would be nice to add inline documentation in 2.0
